services:
  asf:
    image: docker.io/justarchi/archisteamfarm
    container_name: asf
    user: 1000:1000
    volumes:
      - asf:/app/config
    tmpfs:
      - /app/logs
    networks:
      - asf
    labels:
      - io.containers.autoupdate=registry

volumes:
  asf:
    name: asf
    external: true

networks:
  asf:
    external: true
