services:
  prowlarr:
    image: docker.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - TZ=${TIMEZONE}
      - PUID=1000
      - PGID=1000
    volumes:
      - prowlarr:/config
    networks:
      - traefik
    labels:
      - io.containers.autoupdate=registry
      - traefik.enable=true
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN_NAME}`)
      - traefik.http.routers.prowlarr.middlewares=homer-cors@file
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696

volumes:
  prowlarr:
    name: prowlarr
    external: true

networks:
  traefik:
    external: true
