services:
  prowlarr:
    image: docker.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - TZ=${TIMEZONE}
      - PUID=1000
      - PGID=1000
    volumes:
      - prowlarr:/config
    networks:
      - torrent
    labels:
      - io.containers.autoupdate=registry

volumes:
  prowlarr:
    name: prowlarr
    external: true

networks:
  torrent:
    external: true
