services:

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-socket-proxy
    environment:
      - CONTAINERS=1
    security_opt:
      - label=disable
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    labels:
      - io.containers.autoupdate=registry

  traefik:
    depends_on:
      - docker-socket-proxy
    image: traefik:latest
    container_name: traefik
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - traefik:/etc/traefik
    networks:
      - traefik
    labels:
      - io.containers.autoupdate=registry
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)
      - traefik.http.routers.traefik.service=api@internal

volumes:
  traefik:
    name: traefik
    external: true

networks:
  traefik:
    external: true
