services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - TZ=${TIMEZONE}
      - PUID=1000
      - PGID=1000
    volumes:
      - radarr:/config
      - ${HOME}/Movies:/movies:z
      - ${HOME}/Torrents:/downloads:z
    networks:
      - traefik
    labels:
      - io.containers.autoupdate=registry
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_NAME}`)
      - traefik.http.routers.radarr.middlewares=homer-cors@file
      - traefik.http.services.radarr.loadbalancer.server.port=7878

volumes:
  radarr:
    name: radarr
    external: true

networks:
  traefik:
    external: true
