services:
  homer:
    image: docker.io/b4bz/homer
    container_name: homer
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - homer:/www/assets
    networks:
      - homer
    labels:
      - io.containers.autoupdate=registry

volumes:
  homer:
    name: homer
    external: true

networks:
  homer:
    external: true
