services:
  homer:
    image: b4bz/homer
    container_name: homer
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - homer:/www/assets
    networks:
      - traefik
    healthcheck:
      test: [ "NONE" ]
    labels:
      - io.containers.autoupdate=registry
      - traefik.enable=true
      - traefik.http.routers.homer.entrypoints=websecure
      - traefik.http.routers.homer.rule=Host(`homeserver.${DOMAIN_NAME}`)
      - traefik.http.services.homer.loadbalancer.server.port=8080

volumes:
  homer:
    name: homer
    external: true

networks:
  traefik:
    external: true
