services:
  cloudflared:
    image: docker.io/cloudflare/cloudflared
    container_name: cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    networks:
      - archisteamfarm
      - cockpit
      - homer
      - torrent
    labels:
      - io.containers.autoupdate=registry

networks:
  archisteamfarm:
    external: true
  cockpit:
    external: true
  homer:
    external: true
  torrent:
    external: true
