services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - /containers/jellyfin/config:/config:Z
      - /containers/jellyfin/cache:/cache:Z
      - /home/sk/Anime-TV:/tv:z
      - /home/sk/Anime-Movies:/movies:z
    networks:
      - traefik
    labels:
      - io.containers.autoupdate=registry
      - traefik.enable=true
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=letsencrypt
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_NAME}`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

networks:
  traefik:
    external: true
