services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - jellyfin:/config
      - jellyfin-cache:/cache
      - /home/$USER/Anime-TV:/tv:z
      - /home/$USER/Anime-Movies:/movies:z
    networks:
      - traefik
    labels:
      - io.containers.autoupdate=registry
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=letsencrypt
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_NAME}`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

volumes:
  jellyfin:
    name: jellyfin
    external: true
  jellyfin-cache:
    name: jellyfin-cache
    external: true

networks:
  traefik:
    external: true
