services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - jellyfin:/config
      - jellyfin:/cache
      - ${HOME}/TV:/tv:z
      - ${HOME}/Movies:/movies:z
    networks:
      - traefik
    labels:
      - io.containers.autoupdate=registry
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_NAME}`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

volumes:
  jellyfin:
    name: jellyfin
    external: true

networks:
  traefik:
    external: true
