services:

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-socket-proxy
    security_opt:
      - label=disable
    environment:
      - CONTAINERS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - io.containers.autoupdate=registry

  traefik:
    depends_on:
      - docker-socket-proxy
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /containers/traefik/traefik.yml:/traefik.yml:Z
      - /containers/traefik/providers:/providers:Z
      - /containers/traefik/acme.json:/acme.json:Z
    networks:
      - traefik
    labels:
      - io.containers.autoupdate=registry
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)
      - traefik.http.routers.traefik.service=api@internal

networks:
  traefik:
    external: true
