services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - TZ=${TIMEZONE}
      - PUID=1000
      - PGID=1000
    ports:
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - transmission:/config
      - ${HOME}/Torrents:/downloads:z
    networks:
      - traefik
    healthcheck:
      test: [ "NONE" ]
    labels:
      - io.containers.autoupdate=registry
      - traefik.enable=true
      - traefik.http.routers.transmission.entrypoints=websecure
      - traefik.http.routers.transmission.rule=Host(`transmission.${DOMAIN_NAME}`)
      - traefik.http.services.transmission.loadbalancer.server.port=9091

volumes:
  transmission:
    name: transmission
    external: true

networks:
  traefik:
    external: true
