services:
  transmission:
    image: docker.io/linuxserver/transmission
    container_name: transmission
    environment:
      - TZ=${TIMEZONE}
      - PUID=1000
      - PGID=1000
    ports:
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - transmission:/config
      - ${HOME}/Torrents:/downloads:z
    networks:
      - torrent
    labels:
      - io.containers.autoupdate=registry

volumes:
  transmission:
    name: transmission
    external: true

networks:
  torrent:
    external: true
