services:
  kuma:
    image: louislam/uptime-kuma
    container_name: kuma
    cap_add:
      - NET_RAW
    volumes:
      - uptime-kuma:/app/data
    networks:
      - traefik
    healthcheck:
      test: [ "NONE" ]
    labels:
      - io.containers.autoupdate=registry
      - traefik.enable=true
      - traefik.http.routers.kuma.entrypoints=websecure
      - traefik.http.routers.kuma.rule=Host(`kuma.${DOMAIN_NAME}`)
      - traefik.http.services.kuma.loadbalancer.server.port=3001

volumes:
  uptime-kuma:
    name: uptime-kuma
    external: true

networks:
  traefik:
    external: true
